project:
  repo: https://github.com/carlyou/vllm.git

build:
  cuda_arch: "9.0"
  max_jobs: 0.8

test:
  script: tests/kernels/attention/test_merge_attn_states.py
  args: "-v -s -x -k '256-8-256'"

branches:
  test/fp8-atol-1e1:
    build:
      use_precompiled: false
    runs:
      - label: test_fp8_atol
