project:
  repo: https://github.com/carlyou/vllm.git
  model: carlyou/DeepSeek-V2-Lite-FP8-Group

build:
  cuda_arch: "10.0"
  torch_index: https://download.pytorch.org/whl/cu130

server:
  log_level: debug

# 2xB200: debug single failing tp1 test case.

branches:
  test--mla-quant-fusion-group-fp8:
    runs:
      - label: debug_tp1
        test:
          script: tests/compile/fusions_e2e/test_tp1_quant.py
          args: "-v -s --tb=long -k 'inductor_partition and FLASHINFER_MLA and RedHatAI and quant_fp8 and rms_norm and not True'"
