project:
  repo: https://github.com/carlyou/vllm.git
  model: RedHatAI/DeepSeek-Coder-V2-Lite-Instruct-FP8

build:
  use_precompiled: true
  max_jobs: 0.8
  cuda_arch: "9.0"

branches:
  fix/mla-fusion-e2e-tests:
    runs:
      - label: pytest_unit
        test:
          script: tests/models/test_mla.py
          args: "-x -v"
